// <auto-generated />
namespace VirtoCommerce.CatalogPersonalizationModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTaggedItemOutlines : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTaggedItemOutlines));
        
        string IMigrationMetadata.Id
        {
            get { return "201908130739314_AddTaggedItemOutlines"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
